Load dataset using rasterio. Add info method.
GlacioHack/GeoUtils pull request #4
Opened 2020-11-11 16:33 UTC by adehecq

Add steps to __init__ to load the rasterio dataset and copy specific attributes. Add the info method.

2020-11-11 19:24 UTC, iamdonovan submitted a review, later dismissed

2020-11-11 19:27 UTC, iamdonovan approved these changes

2020-11-11 20:17 UTC, atedstone requested changes
Please add an rst docstring to __init__ and info methods. ;)

2020-11-12 09:03 UTC, atedstone approved these changes
Alright, I'll let this one through for now. But we still need those docstrings! :-P

2020-11-12 09:04 UTC, merged